name: Rebase Branch

on:
  workflow_dispatch:
    inputs:
      branch_to_rebase:
        description: 'Branch to rebase'
        required: true
        type: string
      base_branch:
        description: 'Base branch to rebase onto'
        required: true
        type: string
      verbose_output:
        description: 'Verbose output'
        type: boolean

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Rebase branch
        run: |
          chmod +x .github/workflows/rebase.sh
          .github/workflows/rebase.sh ${{ inputs.branch_to_rebase }} ${{ inputs.base_branch }} ${{ inputs.verbose_output }}
