name: Rebase and update SfBlazor.Components

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        type: string
        required: true
      base_branch:
        description: 'Base branch'
        type: choice
        options:
          - Custom (specify below)
          - release/dev
          - release/uat
        required: true
      custom_base_branch:
        description: 'Custom base branch'
        type: string
      sf_blazor_components_branch:
        description: 'SfBlazor.Components branch'
        type: string
        required: true
      squash_sfblazor_components_update_commit:
        description: 'Squash SfBlazor.Components update commit in to previous commit'
        type: boolean
        default: true

jobs:
  merge-to-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve base branch
        id: resolve-base-branch
        run: |
          if [ "${{ inputs.base_branch }}" = "Custom (specify below)" ] && [ -z "${{ inputs.custom_base_branch }}" ]; then
            echo "::error::'Custom base branch' must be specified when 'Custom (specify below)' is selected from the base branch options."
            exit 1
          fi

          resolved_base_branch=$([ "${{ inputs.base_branch }}" = "Custom (specify below)" ] && "${{ inputs.custom_base_branch }}" || echo "${{ inputs.base_branch }}")
          echo "Resolved base branch: ${resolved_base_branch}"
          echo "resolved_base_branch=${resolved_base_branch}" >> $GITHUB_OUTPUT
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify source branch exists
        run: |
          if ! ./.github/workflows/scripts/verify-branch-exists.sh --repository="${{ github.repository }}" --branch="${{ inputs.branch }}"; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch base branch
        run: |
          if ! ./.github/workflows/scripts/fetch-branch.sh --repository="${{ github.repository }}" --branch="${{ steps.resolve-base-branch.outputs.resolved_base_branch }}"; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase branch
        run: |
          if ! ./.github/workflows/scripts/rebase-with-submodule-conflict-resolution.sh --branch="${{ inputs.branch }}" --base-branch="${{ steps.resolve-base-branch.outputs.resolved_base_branch }}" --submodule-path="modules/test-components"; then
            exit 1
          fi
      
      - name: Update submodule
        run: |
          if ! ./.github/workflows/scripts/update-submodule.sh --local-branch="${{ inputs.branch }}" --submodule-repository="${{ github.repository_owner }}/test-components" --submodule-branch="${{ inputs.sf_blazor_components_branch }}" --submodule-path="modules/test-components" --squash-commit="${{ inputs.squash_sfblazor_components_update_commit }}"; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          if ! ./.github/workflows/scripts/push-changes.sh --branch="${{ inputs.branch }}" --dry-run=true --force-push=true; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
