name: Rebase with submodule conflict resolution

on:
  workflow_dispatch:
    inputs:
      branch_to_rebase:
        description: 'Branch to rebase'
        required: true
        type: string
      base_branch:
        description: 'Base branch to rebase onto'
        required: true
        type: string

jobs:
  rebase-with-submodule-conflict-resolution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check branches exist
        run: |
          if ! ./.github/workflows/check-branch-exists.sh ${{ github.repository }} ${{ inputs.branch_to_rebase }}; then
            exit 1
          fi
          if ! ./.github/workflows/check-branch-exists.sh ${{ github.repository }} ${{ inputs.base_branch }}; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Rebase branch
        run: |
          ./.github/workflows/rebase-with-submodule-conflict-resolution.sh ${{ inputs.branch_to_rebase }} ${{ inputs.base_branch }} modules/test-components
