name: Update SfBlazor.Components

on:
  workflow_dispatch:
    inputs:
      v3_branch_name:
        description: "V3 branch"
        required: true
      sfblazor_branch_name:
        description: "SfBlazor.Components branch"
        required: true
      squash_commit:
        description: "Squash the update commit into the previous commit"
        type: boolean
        default: true

jobs:
  update-sf-blazor-components:
    runs-on: ubuntu-latest
    steps:
      - name: Check that branches exist
        run: |
          if ! gh api repos/${{ github.repository }}/branches/${{ inputs.v3_branch_name }} --jq .name 2>/dev/null; then
            echo --escape "\nThe branch ${{ inputs.v3_branch_name }} does not exist in this repository"
            exit 1
          fi
          if ! gh api repos/mark-storefeeder/test-components/branches/${{ inputs.sfblazor_branch_name }} --jq .name 2>/dev/null; then
            echo --escape "\nThe branch ${{ inputs.sfblazor_branch_name }} does not exist in the SfBlazor.Components repository"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.v3_branch_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update SfBlazor.Components submodule
        #if: steps.check-branch.outputs.branch_exists == 'true'
        run: |
          git submodule update --init --recursive
          cd modules/test-components
          git fetch origin ${{ inputs.sfblazor_branch_name }}
          git checkout ${{ inputs.sfblazor_branch_name }}
          cd ../..
          # Force add the submodule changes to resolve any conflicts
          git add --force modules/test-components
          if git diff --staged --quiet; then
            echo 'No changes to commit'
          else
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            if [ "${{ inputs.squash_commit }}" = "true" ]; then
              git commit --amend --no-edit --allow-empty
              git push --force origin ${{ inputs.v3_branch_name }}
            else
              git commit --message "Update SfBlazor to reference ${{ inputs.sfblazor_branch_name }} branch"
              git push origin ${{ inputs.v3_branch_name }}
            fi
          fi
