name: Update SfBlazor.Components

on:
  pull_request:
    types: [labeled]

jobs:
  update-sf-blazor-components:
    if: github.event.label.name == 'ready for dev testing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release/dev branch exists
        id: check-branch
        run: |
          git ls-remote --heads https://github.com/mark-storefeeder/test-components.git release/dev
          if [ $? -eq 0 ]; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update submodule
        if: steps.check-branch.outputs.branch_exists == 'true'
        run: |
          git submodule update --init --recursive
          cd modules/test-components
          git fetch origin release/dev
          git checkout release/dev
          cd ../..
          git add test-components
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m "Update test-components submodule to release/dev branch"
          git push
