name: Update SfBlazor.Components

on:
  workflow_dispatch:
    inputs:
      v3_branch_name:
        description: "V3 Branch"
        required: true
        type: choice
        options:
          - release/dev
          - release/uat
          - other
      v3_other_branch_name:
        description: "'Other' V3 branch name"
        required: false
        type: string
      sfblazor_branch_name:
        description: "SfBlazor.Components branch"
        required: true
        type: choice
        options:
          - release/dev
          - release/uat
          - other
      sfblazor_other_branch_name:
        description: "'Other' SfBlazor.Components branch name"
        required: false
        type: string

jobs:
  update-sf-blazor-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve branch names
        id: resolve-branch-names
        run: |
          echo "v3_branch_name=${{ inputs.v3_branch_name == 'other' && inputs.v3_other_branch_name || inputs.v3_branch_name }}" >> $GITHUB_OUTPUT
          echo "sfblazor_branch_name=${{ inputs.sfblazor_branch_name == 'other' && inputs.sfblazor_other_branch_name || inputs.sfblazor_branch_name }}" >> $GITHUB_OUTPUT

      - name: Check that branches exist
        run: |
          if ! gh api repos/${{ github.repository }}/branches/${{ steps.resolve-branch-names.outputs.v3_branch_name }} --jq .name 2>/dev/null; then
            echo ""
            echo "The branch ${{ steps.resolve-branch-names.outputs.v3_branch_name }} does not exist in this repository"
            exit 1
          fi
          if ! gh api repos/mark-storefeeder/test-components/branches/${{ steps.resolve-branch-names.outputs.sfblazor_branch_name }} --jq .name 2>/dev/null; then
            echo ""
            echo "The branch ${{ steps.resolve-branch-names.outputs.sfblazor_branch_name }} does not exist in the SfBlazor.Components repository"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update SfBlazor.Components submodule
        #if: steps.check-branch.outputs.branch_exists == 'true'
        run: |
          git submodule update --init --recursive
          cd modules/test-components
          git fetch origin ${{ steps.resolve-branch-names.outputs.sfblazor_branch_name }}
          git checkout ${{ steps.resolve-branch-names.outputs.sfblazor_branch_name }}
          cd ../..
          git add modules/test-components
          if git diff --staged --quiet; then
            echo 'No changes to commit'
          else
            gh auth setup-git
            gh api --method POST /repos/${{ github.repository }}/git/commits \
              -f message='Update SfBlazor to reference ${{ steps.resolve-branch-names.outputs.sfblazor_branch_name }} branch' \
              -f author='{"name": "GitHub Actions", "email": "github-actions@github.com"}' \
              -f committer='{"name": "GitHub Actions", "email": "github-actions@github.com"}' \
              --jq .sha | xargs -I {} git push origin {}:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
